# Generated by Django 3.0.3 on 2020-04-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career_level',
            field=models.CharField(blank=True, max_length=2, verbose_name='Career Level'),
        ),
    ]
