# Generated by Django 3.0.3 on 2020-04-13 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200413_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.CharField(choices=[('0', 'Employed'), ('1', 'Resigned')], default='0', max_length=1)),
                ('joined_date', models.DateField(null=True, verbose_name='Joined Date')),
                ('resigned_date', models.DateField(blank=True, null=True, verbose_name='Resigned Date')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
