# Generated by Django 2.2.4 on 2020-04-14 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_accountmaster_employeeassignmenthistory_projectmaster_rolemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignmenthistory',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ids3', to='register.ProjectMaster'),
        ),
        migrations.AlterField(
            model_name='employeeassignmenthistory',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_names3', to='register.ProjectMaster'),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='role_name',
            field=models.CharField(max_length=50, verbose_name='Role Name'),
        ),
    ]
