# Generated by Django 2.2.4 on 2020-04-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200414_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignmenthistory',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='projectmaster',
            name='account_id',
        ),
    ]
