# Generated by Django 2.2.4 on 2020-04-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200414_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignmenthistory',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='employeeassignmenthistory',
            name='role_id',
        ),
    ]
