# Generated by Django 2.2.4 on 2020-04-14 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20200414_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DteMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='DTE ID')),
                ('dte_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='DTE Name')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
        ),
        migrations.AddField(
            model_name='employeeassignmenthistory',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='accountmaster',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='employeeassignmenthistory',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dte_id',
            field=models.CharField(blank=True, max_length=5, verbose_name='IGNORE'),
        ),
        migrations.AddField(
            model_name='user',
            name='dte_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.DteMaster'),
        ),
    ]
