# Generated by Django 2.2.4 on 2020-04-14 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20200414_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategoryMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category_id', models.CharField(max_length=8, verbose_name='Skill Category')),
                ('skill_category_name', models.CharField(max_length=8, verbose_name='Skill Category Name')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date')),
            ],
        ),
        migrations.CreateModel(
            name='SkillMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=8, verbose_name='Skill ID')),
                ('skill_name', models.CharField(max_length=8, verbose_name='Skill Name')),
                ('active_status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=1, verbose_name='Active Status')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date')),
                ('skill_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_category_name1', to='register.SkillCategoryMaster')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ids2', to=settings.AUTH_USER_MODEL)),
                ('skill_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_category_name2', to='register.SkillCategoryMaster')),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_name2', to='register.SkillMaster')),
            ],
        ),
    ]
