# Generated by Django 2.2.4 on 2020-04-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_employeeskills_skillcategorymaster_skillmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategorymaster',
            name='skill_category_name',
            field=models.CharField(max_length=50, verbose_name='Skill Category Name'),
        ),
        migrations.AlterField(
            model_name='skillmaster',
            name='skill_name',
            field=models.CharField(max_length=50, verbose_name='Skill Name'),
        ),
    ]
