# Generated by Django 2.2.4 on 2020-04-15 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20200414_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.CharField(max_length=50, verbose_name='Role Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('exp_detail', models.CharField(max_length=200, verbose_name='Exp Detail')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ids7', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
