# Generated by Django 2.2.4 on 2020-04-15 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_employeejobhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('vendor_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Vendor Id')),
                ('vendor_name', models.CharField(max_length=50, verbose_name='Vendor Name')),
                ('active_status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=1, verbose_name='Active Status')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMaster',
            fields=[
                ('training_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Training Id')),
                ('training_name', models.CharField(max_length=50, verbose_name='Training Name')),
                ('active_status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=1, verbose_name='Active Status')),
                ('registered_date', models.DateField(blank=True, null=True, verbose_name='Registered Date')),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_name1', to='register.VendorMaster')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTrainingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ids3', to=settings.AUTH_USER_MODEL)),
                ('training_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_name1', to='register.TrainingMaster')),
            ],
        ),
    ]
