# Generated by Django 2.2.4 on 2020-04-15 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_employeetraininghistory_trainingmaster_vendormaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejobhistory',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AddField(
            model_name='employeetraininghistory',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AddField(
            model_name='vendormaster',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='career_level',
            field=models.CharField(choices=[('0', 'CL1'), ('1', 'CL2'), ('2', 'Cl3'), ('3', 'CL4'), ('4', 'CL5'), ('5', 'CL6'), ('6', 'CL7'), ('7', 'CL8'), ('8', 'CL9'), ('9', 'CL10'), ('10', 'CL11'), ('11', 'CL12'), ('12', 'CL13')], default='0', max_length=4),
        ),
    ]
